// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelValue } from "./ChannelValue";
import type { Mode } from "./Mode";

/**
 * Controller → plant: the proposed actuation, with `mode`/`ttl_ms` safety
 * metadata. `seq` should echo the originating `SensorFrame.seq`.
 */
export type CommandFrame = { ncp_version: string, kind: string, seq: bigint, t: number, frame_id: string, mode: Mode, ttl_ms: number, channels: { [key in string]: ChannelValue }, };
