// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";

/**
 * Binds a client entity to a stimulus or record port.
 */
export type EntityBinding = { entity: EntityRef, port: string, 
/**
 * `"stimulus"` | `"record"`.
 */
direction: string, };
