// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRole } from "./EntityRole";

/**
 * A hierarchical client-side entity address, e.g. `crebain/uav3/sensor/cam0`.
 */
export type EntityRef = { path: string, role: EntityRole, meta: { [key in string]: string }, };
