// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controller mode (the safety-critical action authority lives here).
 */
export type Mode = "init" | "active" | "hold" | "estop";
