// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of network reference `NetworkRef.ref` is.
 */
export type NetworkRefKind = "handle" | "builtin" | "model_id" | "spec";
