// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Observation } from "./Observation";

/**
 * The returned neural data, keyed by record port.
 */
export type ObservationFrame = { ncp_version: string, kind: string, session_id: string, t: number, sim_time_ms: number, records: { [key in string]: Observation }, calibrated_posterior: boolean, is_simulation_output: boolean, };
