// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Observable } from "./Observable";

/**
 * Recorded data for one record port. `times`+`values` are parallel for analog;
 * `times`+`senders` are parallel for spikes.
 */
export type Observation = { port: string, target: string, observable: Observable, times: Array<number>, values: Array<number>, senders: Array<bigint>, unit: string | null, };
