// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to record off a population/neuron/synapse.
 */
export type Observable = "spikes" | "V_m" | "rate" | "weight";
