// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordTarget } from "./RecordTarget";

export type RecordSpec = { targets: Array<RecordTarget>, };
