// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Observable } from "./Observable";

/**
 * One recording: client `port` name ← `observable` of `target` population.
 */
export type RecordTarget = { port: string, target: string, observable: Observable, ids: Array<bigint>, cadence_ms: number, };
