// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who a peer is in the closed-loop handshake.
 */
export type Role = "controller" | "plant";
