// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StimulusFrame } from "./StimulusFrame";

/**
 * Batch: advance `duration_ms` holding a stimulus; returns an `ObservationFrame`.
 */
export type RunRequest = { ncp_version: string, kind: string, session_id: string, duration_ms: number, stimulus: StimulusFrame | null, };
