// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bounds the action plane. Only the command path enforces these.
 */
export type SafetyLimits = { max_speed_mps: number | null, max_tilt_rad: number | null, geofence_radius_m: number | null, command_timeout_ms: number, };
