// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionClosed = { ncp_version: string, kind: string, session_id: string, ok: boolean, };
