// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelValue } from "./ChannelValue";

/**
 * The values to inject this step (keyed by stimulus port).
 */
export type StimulusFrame = { ncp_version: string, kind: string, session_id: string, t: number, values: { [key in string]: ChannelValue }, };
