// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StimulusKind } from "./StimulusKind";

/**
 * One stimulus input port.
 */
export type StimulusTarget = { port: string, target: string, kind: StimulusKind, ids: Array<bigint>, };
